### PR TITLE
Enable spack installation on centos 8

### PR DESCRIPTION
**Pull request by IgorBaratta**
This is a known issue, but I don't know if we have a better solution at the moment.
This doesn't affect runtime performance, and the size of the pybind wrapper changes only slightly.

### CODE REVIEW

**Comment by chrisrichardson** [comment]
I am not convinced this is a general problem on Centos8.

**Comment by jhale** [comment]
Can you give some links to these known issues? Would be good to find out a bit more about the problem before turning this off.

**Comment by IgorBaratta** [comment]
> Can you give some links to these known issues? Would be good to find out a bit more about the problem before turning this off.

I was not able to reproduce the issue on an isolated system.
With LTO basix (python) crashes on our local cluster with Centos 8.

As an work around I'm using ```-DCMAKE_INTERPROCEDURAL_OPTIMIZATION=OFF```.
I think this should be an option on spack.

**Comment by jhale** [comment]
I know that this can be caused using mismatched compilers e.g. anaconda compilers to build system python libraries and executable, and system compiler to build the pybind11 library.

**Pull request closed without merging**
