### PR TITLE
Avoid dividing by zero

### PR DESCRIPTION
**Pull request by massimiliano-leoni**
`h` was 1 / 0 for DG0 elements. Although `h` was never actually used when `n == 0`, this triggered some annoying floating-point exception traps while debugging.

### CODE REVIEW

**Review by mscroggs — APPROVED** [review]

**Comment by chrisrichardson** [comment]
I'd rather just put `h` inside the `case` for each cell type.

**Comment by massimiliano-leoni** [comment]
@chrisrichardson I don't mind either way.

**Comment by chrisrichardson** [comment]
@massimiliano-leoni - can you try it the other way? I think `h` is only used by interval, quadrilateral and hexahedron anyway.

**Comment by massimiliano-leoni** [comment]
@chrisrichardson there you have it!

**Review by mscroggs — APPROVED** [review]

**Review by chrisrichardson — APPROVED** [review]

**Pull request merged**
