### PR TITLE
Enum to string

### PR DESCRIPTION
**Pull request by ampdes**
This is only done for the lagrange variant at the moment.

### CODE REVIEW

**Comment by francesco-ballarin** [comment]
Similar string to enum functions used to be available in basix, but were removed in #832 by @garth-wells.

Please give us more context on why you need those conversion functions to be reinstated, otherwise it's unlikely we'll decide to (basically) revert #832 and accept this PR.

**Comment by ampdes** [comment]
If this is really necessary is too early to speak about.
This is needed in adios2 based checkpointing to store the enum types as strings.

I will then try to use maps, as is currently done in the C++ demo.

**Comment by garth-wells** [comment]
> If this is really necessary is too early to speak about. This is needed in adios2 based checkpointing to store the enum types as strings.
> 
> I will then try to use maps, as is currently done in the C++ demo.

If something is needed only in the implementation, put it in an anonymous namespace, make private, etc.

**Comment by garth-wells** [comment]
Closing for now.

**Pull request closed without merging**
