### PR TITLE
Add information about highest degree of polynomials in a finite element

### LINKED ISSUE #345: Add information about highest order polynomial in space
Can be used to find appropriate interpolation spaces.

### PR DESCRIPTION
**Pull request by mscroggs**
Store two number in FiniteElement:

- `highest_polynomial_degree` gives the degree of the Lagrange space that the element is a subspace of.
- `highest_complete_polynomial_degree` gives the degree of the Lagrange space that is a subspace of the element.

`highest_polynomial_degree` will be particularly useful as it tells us which degree Lagrange space to interpolate into for visualising a function

Fixes #345.

### CODE REVIEW

**Comment by mscroggs** [comment]
The names given to these two values may need more thought

**Review by garth-wells — COMMENTED** [review]
Function names are a bit of a mouthful could we shorten? Would it work to have a function 
```cpp
std::array<int, 2> degree();
```
that returns (lower bound, upper bound) on the degree?

**Comment by mscroggs** [comment]
> Would it work to have a function
> 
> ```c++
> std::array<int, 2> degree();
> ```
> 
> that returns (lower bound, upper bound) on the degree?

Good idea

**Comment by garth-wells** [comment]
> Good idea, except we already have `degree()` that returns the degree passed in when creating the space

Which degree do we pass in - the 'lower' or 'upper' bound?

**Comment by mscroggs** [comment]
> Which degree do we pass in - the 'lower' or 'upper' bound?

Depends on the element. Ususally we pass in the lower bound, but for some elements (eg serendipity) we pass in something else.

I'm calling this `degree_bounds` for now

**Review by garth-wells — APPROVED** [review]

**Pull request merged**
